#!/bin/bash

# Includes
. utils

# Handlers
on_dvr() {
    echo "Content-Type: text/html"
    echo ""
    for file in /mnt/extsd/movies/*.ts; do
        body="$body $(echo "$(ls -l $file)" | awk '{printf "{\"date\":\"%s %s %s\",\"size\":%s,", $6,$7,$8,$5}')"
        body="$body \"file\":\"${file##*/}\",\"jpg\":\"$(base64 ${file%.*}.jpg)\","
    done
    echo "{ \"dvr\":[ $body ] }"
}

on_dvr_download() {
    echo "Content-Type: text/html"
    echo ""
    echo "Download command not implemented"
}

on_dvr_play() {
    echo "Content-Type: text/html"
    echo ""
    echo "Play command not implemented"
}

on_dvr_stop() {
    echo "Content-Type: text/html"
    echo ""
    echo "Stop command not implemented"
}

# Parse Request
if [ -z $QUERY_STRING ]; then
    on_dvr
else
    if contains "$QUERY_STRING" "download"; then
        on_dvr_download
    elif contains "$QUERY_STRING" "play"; then
        on_dvr_play
    elif contains "$QUERY_STRING" "stop"; then
        on_dvr_stop
    fi
fi
