#!/bin/bash

# Includes
. ./constants
. ./utils

# Handlers

# Send the entire settings file
on_settings() {
    content_json
    #utils_is_action_authorized "${HTTP_COOKIE#token=}"
    if test -f ${SETTING_PATH}; then
        count=0
        body=""
        while read line; do
          ((count++))
          if [ ! -z "${line}" ]; then
              IFS="=" read key value <<< "$line"
              if [ ! -z "${key}" ] && [ ! -z "${value}" ]; then
                # settings
                settings="${settings} {\"key\":\"${key}\" \"value\":\"${value}\"},"
              elif [ ! -z "${key}" ] && [ $count -gt 1 ]; then
                # sections
                settings="${settings%?}"
                body="${body} \"${section}\": [ $settings ],"
                section=$(echo "$key" | sed 's/[][]//g')
                settings=
              else
                # first section
                section=$(echo "$key" | sed 's/[][]//g')
              fi
          fi
	done < "$SETTING_PATH"
	settings="${settings%?}"
	body="${body} \"${section}\": [ $settings ]"
	echo "{ \"file\": { $body } }"
   else
      print_error "Status: 404" "Settings file not found."
   fi
}

# Send a settings with line number
on_line_read() {
  content_json
  #utils_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH}; then
     while read line; do
        IFS="=" read key value <<< "$line"
	if [ "$key" = "$1" ]; then
           setting="{\"key\":\"${key}\", \"value\":\"${value}\"}"
	   break
	fi
     done < <(sed -n "/\[$2\]/,/\[/p" "$SETTING_PATH" | grep -v "\[[A-Z]*[a-z]*\]" )
     echo "{ \"$2\": $setting }"
  else
     print_error "Status: 404" "Settings file not found."
  fi
}


# Send a settings section with line numbers
on_section_read() {
    content_json
    #utils_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH}; then
     settings=""
     while read line; do
        IFS="=" read key value <<< "$line"
        if [ ! -z "${key}" ] && [ ! -z "${value}" ]; then
           # settings
           settings="${settings} { \"key\": \"${key}\", \"value\": \"${value}\" },"
        fi
     done < <(sed -n "/\[$1\]/,/\[/p" "$SETTING_PATH")
     settings="${settings%?}"
     echo "{ \"$1\": [ $settings ] }"
  else
      print_error "Status: 404" "Settings file not found."
  fi
}

# Change a setting by line number
on_setting_change() {
   echo "Content-Type: text/html"
   echo ""
   #utils_is_action_authorized "${HTTP_COOKIE#token=}"
   if test -f ${SETTING_PATH}; then
      sed -i "${1}s/.*/${2}/" "$SETTING_PATH"
      if [ $? -eq 0 ]; then
	 echo "Status: 200 OK"
      else
	 echo "Status: 500"
      fi
   else
      echo "Status: 401"
   fi
}

# Add a setting at line number, move everthing after down one line
on_setting_insert() {
  echo "Content-Type: text/html"
  echo ""

  #utils_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH}; then
     sed -i "${1}i ${2}" "$SETTING_PATH"
     if [ $? -eq 0 ]; then
	echo "Status: 200 OK"
     else
	echo "Status: 500"
     fi
  else
     echo "Status: 401"
  fi
}

# Delete a setting at line number, move everthing after up one line
on_setting_delete() {
  echo "Content-Type: text/html"
  echo ""
	  
  #utils_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH}; then
     sed -i "${1}d" "$SETTING_PATH"
     if [ $? -eq 0 ]; then
	echo "Status: 200 OK"
     else
	echo "Status: 500"
     fi
  else
     echo "Status: 401"
  fi
}

# backup the setting file to the sdcard, overwrite
on_backup() {
  echo "Content-Type: text/html"
  echo ""
	  
  #utils_is_action_authorized "${HTTP_COOKIE#token=}"
  if test -f ${SETTING_PATH} -a ! -z "$(mount | grep ${SDC_PATH})"; then
     cp ${SETTINGG_PATH} "${SDC_PATH}settings.bak"
     if [ $? -eq 0 ]; then
	echo "Status: 200 OK"
     else
	echo "Status: 500"
     fi
  else
     echo "Status: 401"
  fi
}

echo "qs: $QUERY_STRING" > debug

# Parse Request
if [ -z $QUERY_STRING ]; then
   on_settings
else
    IFS="&"
    set -- $QUERY_STRING
    key="${1%=*}"
    if [ "$REQUEST_METHOD" = "GET" ]; then
       if [ ${key} == "line" -a "${2%=*}" == "section" ]; then
	  on_line_read "${1#*=}" "${2#*=}" 
       elif [ ${key} == "section" ]; then
          on_section_read "${1#*=}"
       else
          print_error "421 Misdirected Request" "Use only line, section or null."
       fi
    elif [ "$REQUEST_METHOD" = "POST" ]; then
       if [ "$CONTENT_LENGTH" -gt 0 ]; then
          read -n $CONTENT_LENGTH POST_DATA <&0
          case ${key} in
          put)
              if [ ${1#*=} == "line" ]; then
          print_error "000" "Needs development."
              elif [ ${1#*=} == "section" ]; then
          print_error "000" "Needs development."
              else
                 print_error "421 Misdirected Request" "Use only line, section or file."
              fi
            ;;
          post)
          print_error "000" "Needs development."
            ;;
          patch)
          print_error "000" "Needs development."
            ;;
          delete)
          print_error "000" "Needs development."
         ;;
          *)
              print_error "421 Misdirected Request" "Use only put, post, patch, delete."
           ;;
         esac
       else
          print_error "501 Not Implemented" "Use only GET or POST."
       fi
    else
       print_error "501 Not Implemented" "Method is not recognized. Use only GET or POST."
    fi
fi

